# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'appMdc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for appMdc
  #pod 'Firebase/Core'
  #pod 'Firebase/Messaging'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
#  'RCTBridge',
    'DevSupport',
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  #target 'appMdc-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

  target 'appMdcTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == "React"
          target.remove_from_project
      end
  end
end

target 'appMdc-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for appMdc-tvOS

  target 'appMdc-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
